feat-home-page
duofinder/frontend pull request #5
Opened 2023-04-04 21:50 UTC by vitusilva

a vida é mais que isso.

2023-04-04 22:04 UTC, Tryelson commented on src/pages/home/index.tsx
> +        <ul className='links'>
Acredito que aqui vc tenha invertido o nome das classes, essa ul deveria ter um className de "List"

2023-04-04 22:05 UTC, Tryelson commented on src/pages/home/index.tsx
> +              <li className='list'>
Aqui nos itens da lista, o nome da classe poderia ser "list-item", "link", "list-link-item"

2023-04-04 22:06 UTC, Tryelson commented on src/pages/home/index.tsx
> +            <div className="h2">
A classe dessa div deveria ser algo como "box-title", e nao referenciando uma tag como o h2

2023-04-04 22:06 UTC, Tryelson commented on src/pages/home/index.tsx
> +                <h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero nisi facere eos ratione porro modi nostrum necessitatibus eligendi excepturi esse? Praesentium velit dicta vel accus
aqui vc poderia por uma classe, e nao usar o css diretamente na tag

2023-04-04 22:07 UTC, Tryelson commented on src/pages/home/index.tsx
> +            <div className="description">
O mesmo caso daqui, a div poderia se chamar "box-description" e o 'p' embaixo dela deveria ser o "description"

2023-04-04 22:08 UTC, Tryelson commented on src/pages/home/index.tsx
> +            <div className="button">
a div em si nao pode ser chamada por nome de alguma tag, como o button, ao inves disso, vc poderia chamar ela de "box-btn"

Eu vivo citando o "box" pq a div nada mais é que uma caixa, que serve para englobar elementos

2023-04-04 22:09 UTC, Tryelson commented on src/pages/home/index.tsx
> +
O código em si tem muitos espaços em branco, bom dar uma olhadinha nisso

2023-04-04 22:09 UTC, Tryelson commented on src/styles/home-page.scss
> +        padding: 10px 25px 10px 25px;
vc poderia resumir esse padding usando:
padding: 10px 25px;
Dessa forma, nao fica redundante como a linha que vc colocou

2023-04-04 22:10 UTC, Tryelson commented on src/styles/home-page.scss
> +padding: 400px;
um padding tão alto assim em pixel pode ser um problema, depois revisamos isso

2023-04-04 22:12 UTC, Tryelson commented on src/styles/home-page.scss
> +color: rgb(255, 255, 255);
todos esses css de:
font-weight, line-height, font-size, color... que sao estilos pra texto em si, nao se deve ficar colocando em seletores que nao sao de texto, vc deve separar as responsabilidades de cada classe. Ao inves disso, vc poderia ter chamado a classe da tag de texto, e colocar esses estilos diretamente nela

2023-04-04 22:12 UTC, Tryelson commented on src/styles/home-page.scss
> +    padding: 10px 25px 10px 25px;
mesma dica:
padding: 10px 25px;

2023-04-04 22:13 UTC, Tryelson commented on src/styles/home-page.scss
> +    width: 30%;
revisar esse width para esse botao aqui, pois ele sempre ficara pegando 30% em relacao ao tamanho do pai, e nao é o ideal

2023-04-04 22:14 UTC, Tryelson requested changes
Pontuei algumas linhas para serem corrigidas...

2023-04-07 00:43 UTC, tckthecreator approved these changes

2023-04-07 12:41 UTC, tckthecreator requested changes

2023-04-07 12:41 UTC, tckthecreator commented on src/styles/home-page.scss
> +    background: linear-gradient(#371a54 , #2d005a, #262b5e);
#371a54 deveria ser uma variável global

mais info com @Tryelson

2023-04-08 18:49 UTC, Tryelson approved these changes

2023-04-08 20:24 UTC, tckthecreator approved these changes

2023-04-08 20:25 UTC, merged